version: "3.7"

services:
  grafana-server:
    container_name: grafana
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana.ini

  nginx:
    container_name: nginx
    image: nginx:latest
    # user: "1000"
    ports: 
      - 8080:8080
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
